### ISSUE TITLE
Feature request: Add more features to #ifdef

### ISSUE THREAD

**Issue by LeonarthCG** [FireEmblemUniverse/ColorzCore#17]
I think being able to do different stuff in the buildfile based on the value of a definition would be useful, even though it could end up being pretty niche, so I don't think it's a high priority feature at all.

If we could check if the value the definition has at that moment is above a certain number we could do stuff like not installing certain engine hacks in the skill system if a skill has been defined to 0xFF which would save a bit of space, preserve vanilla functionalities or speed up the building process a tiny bit.

A different way this could be done is by using something like a #defineif which would only define something if the conditions are met (and would otherwise do nothing, like #undef).

**Comment by StanHash** [comment]
:thinking: 

First, what is the reasoning behind using `#define SkillXyzID 0xFF` and using this hypothetical conditional `#ifdef` instead of just not defining `SkillXyzID` and using good old regular `#ifdef`? I'm not trying to dismiss the idea of more complex preprocessor conditionals but I don't see why this would be necessary in *this* particular case...

Anyway this whole thing sounds very much similar to C `#if`; which takes an arbitrary expression that's valid in C (I think) and does stuff if the result is non-zero. Since the EA preprocessor is already heavily based on C's in syntax maybe doing the whole `#if` thing would be the way to go?

`#defineif` however I really don't know about. Why not do this:

```c
#if <expression> // or #ifdef <identifier>
  #define <stuff>
#endif
```

Afaik as I understand it, it's the same thing. If the idea is to provide a short cut to that I think all it would do is make things harder to read.

**Comment by LeonarthCG** [comment]
I don't really know why I thought this would be better than using #ifdef, I had this idea really late into the night.

Maybe I was thinking changing it to 0xFF is easier because then you don't need to add as many #ifdefs (things like the skill being in a list wouldn't be a problem since 0xFF always returns false), or maybe I thought it would be less confusing for users to tell them to set skills they don't want to 0xFF instead of telling them that removing some is ok, but others aren't (like canto or the start of turn hp healing skills).
